### ISSUE TITLE
Implementation based on NODE_14_X which is no longer supported

### ISSUE THREAD

**Issue by pslootweg** [HarshRohila/cdk-secure-parameter-store#10]
During deployment error:

`Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions.`

**Comment by HarshRohila** [comment]
This issue can be fixed by updating CDK version used when running "cdk deploy" in your app using this library. I updated the CDK version in this library too for testing purpose

**Comment by pslootweg** [comment]
I am using up-to-date CDK. 
also not sure how that would fix it since the Node version is hardcoded in this library.
